name: Flutter Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  releaseAndroid:
    name: Release Android for F-Droid
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.27.0"

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Build Unsigned APK
        run: flutter build apk --release --flavor fdroid

      - name: Upload Unsigned APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fdroid-release-apk
          path: build/app/outputs/flutter-apk/app-fdroid-release.apk